######################## default configuration ####################
baseURL = "https://www.chenfeitech.com/"
title = "深圳市辰霏软件技术有限公司"
theme = "bigspring-light"
 # copyright
copyright = "Copyright © 2024 深圳市辰霏软件技术有限公司 all rights reserved.【 <a href='https://beian.miit.gov.cn/' target='_blank'>粤ICP备2021156154号-1</a> 】"

# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"

# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
    unsafe = true

[languages]
    [languages.en]
        contentDir = "content/english" # content/english
        languageName = "中文"
        title = "深圳市辰霏软件技术有限公司"
        [languages.en.params]
            footer_menu_left = "公司介绍"
            footer_menu_middle = "产品服务"
            footer_menu_right = "服务支持"
           
