# main menu
[[main]]
name = "首页"
url = "/"
weight = 1

[[main]]
name = "公司博客"
url = "blog"
weight = 2

[[main]]
name = "产品定价"
url = "pricing"
weight = 3

[[main]]
name = "联系我们"
url = "contact"
weight = 4

[[main]]
name = "FAQ"
url = "faq"
weight = 5

# footer menu left
[[footer_left]]
name = "关于我们"
url = "#"

[[footer_left]]
name = "快速开始"
url = "#"


# footer menu middle
[[footer_middle]]
name = "产品定价"
url = "pricing"

[[footer_middle]]
name = "软件产品"
url = "#"

[[footer_middle]]
name = "技术服务"
url = "#"

# footer menu right
[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy"

[[footer_right]]
name = "服务条款"
url = "terms-conditions"

[[footer_right]]
name = "FAQ"
url = "faq"