# main menu
[[main]]
name = "首页"
url = "/"
weight = 1

[[main]]
name = "公司博客"
url = "#"
weight = 2
# url = "blog"

[[main]]
name = "产品定价"
url = "#"
weight = 3
# url = "pricing"

[[main]]
name = "联系我们"
url = "contact"
weight = 4

[[main]]
name = "FAQ"
url = "#"
weight = 5
# url = "faq"

# footer menu left
[[footer_left]]
name = "关于我们"
url = "#"

[[footer_left]]
name = "快速开始"
url = "#"


# footer menu middle
[[footer_middle]]
name = "产品定价"
url = "#"
# url = "pricing"

[[footer_middle]]
name = "软件产品"
url = "#"

[[footer_middle]]
name = "技术服务"
url = "#"

# footer menu right
[[footer_right]]
name = "隐私政策"
url = "#"
# url = "privacy-policy"

[[footer_right]]
name = "服务条款"
url = "#"
# url = "terms-conditions"

[[footer_right]]
name = "FAQ"
url = "#"
# url = "faq"